### PR TITLE
Added progress (ika).

### PR DESCRIPTION
**Pull request by niyari**
While waiting for the data to be collected, display something that users can enjoy.

If we could guarantee that computers in all countries could display UTF-8, we might have been able to display something a little more realistic.
くコ:彡 ～～～

image

image

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Wow, I love this so much! So cute, what a great idea!!! I'll try it out later. :) This is the best PR I have ever received.

(Since they removed it from the game, maybe s3s should feature Squid Beatz 3……)

**Comment by frozenpandaman** [comment]
btw, I think we can count on UTF-8 support! 👍

https://github.com/frozenpandaman/s3s/blob/eb96e22df3b95b7bfa34fb929148ba0033b5c038/s3s.py#L18-L19
https://twitter.com/frozenpandaman/status/1574634875189022720

**Comment by niyari** [comment]
I limited the display characters so that s3s can be used without problems even on a computer that can only use Latin-1.
This commit only shows progress in minimal places.
Since there is no progress indication of uploads, etc., we need to add or change enough code to confirm that s3s is working properly, depending on the status of future feature additions.

(イカラジオ, come back to the terminal in the lobby.)

**Comment by frozenpandaman** [comment]
I think `>=>`  → `===>` looks the best anyway, like a squid swimming. :) If you have other cute ideas or ways to animate this differently please let me know!

**Comment by frozenpandaman** [comment]
@niyari Do you know if there's a way to clear/hide the squid after `fetch_json()` completes, before it returns?

image

**Comment by niyari** [comment]
If not used in `main()` , I would like to use the destructor.

```
import sys
import time

class Progress:
    def __init__(self):
        self.count = 0
        self.lineend = 31

    def __call__(self):
        ika = '>=> ' if self.count % 2 == 0 else '===>'
        sys.stdout.write("\r%s%s%s" % (' ' * self.count, ika,' ' * (self.lineend - self.count)))
        sys.stdout.flush()
        self.count += 1
        if(self.count > self.lineend):
            self.count = 0

    def __del__(self):
        sys.stdout.write("\r%s\r" % (' ' * (self.lineend + 4))) # '>=> ' or '===>' = 4
        sys.stdout.flush()

def sub_1():
    print("Sub1")
    progress = Progress()
    sub_2()
    print("Sub2 end")
    for i in range(10):
        progress()
        time.sleep(0.3)

def sub_2():
    print("Sub2")
    progress = Progress()
    for i in range(10):
        progress()
        time.sleep(0.3)

def main():
    print("Progress ika")
    progress = Progress()
    sub_1()
    print("Sub1 end")
    for i in range(10):
        progress()
        time.sleep(0.3)

main()
print("Progress end")
```

**Comment by frozenpandaman** [comment]
@niyari That looks good! I'll be doing some code refactoring soon (by v0.2.0) to move all currently-bare code into `main()` so that s3s can be imported by other scripts without `config.txt` being created and stuff being printed (see #17). Once I do this, please let me know if you think the `sub_1()`/`sub_2()` structure would benefit the script & look better to users.

**Pull request merged**
