### PR TITLE
Fix: #99

### PR DESCRIPTION
**Pull request by unyacat**
Check #99 about this change.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
thank you!

**Comment by frozenpandaman** [comment]
Oops! Note that this is not valid Python: https://docs.python.org/3/tutorial/errors.html#handling-exceptions

The line should read
```python
except (KeyError, TypeError):
```

I'll make this change, but just to note for the future!

**Comment by unyacat** [comment]
Thanks for the correction and note, I'm really sorry.

**Comment by frozenpandaman** [comment]
@unyacat No problem at all! :D

**Pull request merged**
