### PR TITLE
fix the salmon run query hash

### PR DESCRIPTION
**Pull request by beanjamin25**
The salmon run query hash seems to have been updated for v4.0.0

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Hmmm... there's a tool that does the query diffs automatically and it didn't detect this one as having changed. Does the old one still work? Or did you discover this after getting an error, and finding the new hash yourself? Will look into it, thank you.

**Comment by M1N0RM1N3R** [comment]
Tested this myself, I can confirm that it works.

**Comment by niyari** [comment]
There is no hash value change for CoopHistoryDetailQuery, so it can be considered a minor change or preparation for the next change.
Once the changes in this revision have been sorted out, you may find other places that need to be changed.

**Comment by frozenpandaman** [comment]
Ahh, I see, the hash was updated previously and I just didn't catch it, so it wasn't included in the diff this time around.

Thanks!!

**Pull request merged**
