### PR TITLE
Record played time and skip fetched results

### PR DESCRIPTION
**Pull request by zhxie**
The patch wil add a new config field `last_played_time` for recording `playedTime` field of battles and jobs.

When fetching JSON,

- latest battles will be checked during overview phase, so that fetched battles will not be requested again,
- regular battles, anarchy battles, private battles will be checked during detail phase, so there will be only 1 fetched battle will be requested again,
- jobs will be checked during detail phase, so there will be only 1 fetched job will be requested again.

At last, `last_played_time` will be updated and reloaded.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Hi @zhxie, sorry for the late reply! I talked with @clovervidia and I don't think we understand exactly what this does – sorry! Can you help me understand? Or why do we want to record `latest_played_time` (i.e. the time your most recent battle started), why is this important, i.e. what will this new config variable be used for? I don't see it actually changing functionality of anything anywhere.

**Comment by zhxie** [comment]
Well, `latest_played_time` is the last `playedTime` seen in fetched JSON by `s3s`. #10 asked to track last battle/job's `id` so we can only fetch new battles/jobs to accelerate `s3s`, but I am not sure whether it is unique globally or not, and whether it is generated randomly or in a certain order.

As a result, I decided to track `playedTime` since it is absolutely unique and orderly. In the patch, when `s3s` decides to fetch JSONs, it will see if the fetched `playedTime` is equal or earlier than the recorded one, and skip the corresponding and subsequent results.

E.g.,

```
CONFIG_DATA["last_played_time"] = "2022-10-20T10:00:00+00:00"
battles_ids = [ "4", "3", "2", "1" ]
fetch "4" -> "playedTime" = "2022-10-21T15:00:00Z" -> append
fetch "3" -> "playedTime" = "2022-10-20T18:00:00Z" -> append
fetch "2" -> "playedTime" = "2022-10-20T10:00:00Z" -> break
```

**Comment by frozenpandaman** [comment]
Ahhh, so it'd be used to improve `-o` and speed up that process overall, that makes sense! That command _is_ meant to be temporary until stat.ink supports Tricolor Turf War Splatfest battles & Salmon Run data… but I'm not sure how long that will be.

Battles are fetched from most recently played (newest) to least recently played (oldest), the same top-to-bottom order they are shown in SplatNet 3. Battle `id`s (Base64-encoded) are unique but so are timestamps, and this makes sense as something user-readable to record.

I'll sync back up with @clovervidia but imo calling this something like `"last_export_time"` would be good and then we can make it _only_ generate & be checked when running with `-o`, and not with other arguments like `-M` or `-r`. And I think if it's specified in `config.txt` we'll want to use it to make the run potentially shorter (i.e. only export results after that time), but if it's not then `-o` just runs normally – it won't be a _required_ value in config.txt (only people who run `-o` will ever get it in theirs).

**Comment by clovervidia** [comment]
Instead of storing the time as a string and performing that string replacement on the times from SplatNet 3 to use `datetime.datetime.fromisoformat`, do you think it be easier to use Unix timestamps? There's already a function in `utils.py`, `epoch_time`, that can parse the SplatNet 3 times and return a timestamp from them.

**Comment by zhxie** [comment]
@clovervidia sounds great, I will fix the patch soon.

@frozenpandaman I think maybe in monitoring mode we still need the feature, so that we can skip fetched result when startup (where there is no cached result)?

**Comment by zhxie** [comment]
@frozenpandaman sorry for late. I have updated patch, can you take a look?

**Comment by frozenpandaman** [comment]
@zhxie Thanks for updating it! School is pretty busy, more than anticipated, but I will try to get to it this week.

**Comment by zhxie** [comment]
Since we are now using multithreading to fetch results, it is maybe not neccessary and not available to track and skip recorded.

**Comment by frozenpandaman** [comment]
@zhxie That's a good point. My JSONs are exporting pretty quickly now. I'm not opposed to this per se (just haven't had time to really test it) but making `fetch_json()` more and more complicated, with an increasing number of arguments, adds to the overall complexity and I'm kind of shying away from that. If you think `-o` is also working fast enough for you – you should really only need to use it during Splatfests, since everything else is supported by stat.ink, including the recent addition of X Battles – let me know and feel free to close the PR.

Thank you so much for your work though, greatly appreciated!!! 🙏

**Pull request closed without merging**
