### PR TITLE
add support for ver.6.0.0 new SR specials & update NSO app version and splatnet 3 version hash

### PR DESCRIPTION
**Pull request by qjzcj2008**
I add support for new SR SPs added in ver6.0.0, and updated NSO app fallback version & splatnet 3 version hash.

And tested on my side it works fine.

### CODE REVIEW

**Comment by Lokno** [comment]
Pulled this branch and tested it. Successfully uploaded all my un-uploaded jobs which were producing the unknown special error.

**Comment by frozenpandaman** [comment]
Thank you! I'm traveling and don't have a computer with me but this all looks good and I can get it merged tonight. Can you bump the version to `0.6.0` as well?

**Comment by cesaregarza** [comment]
There's no X Power changes that the existing logic does not handle, it's a change done on how the X Power is calculated, but on the NSO view there shouldn't be any change iirc.

**Comment by frozenpandaman** [comment]
The SR changes were already included in #156 and I've just merged that PR.

**Comment by frozenpandaman** [comment]
I'll actually update to 0.6.0 later (in a couple days) to include a few other PRs, so can merge this now.

**Pull request merged**
