### PR TITLE
Call Improvements and Refactoring.

### PR DESCRIPTION
**Pull request by niyari**
Header generation was improved and made 160% faster(Swim Speed Up).
In addition, the header for obtaining the version has been changed to more closely resemble that of the actual device.

### CODE REVIEW

**Comment by clovervidia** [comment]
Sorry to keep you waiting. I like the idea of storing the user agent in `s3s.py` and passing it to the other functions instead of having it duplicated in the other modules. That should make it easier to update in the future if needed.

However, I'm not so sure about moving some of the web view logic out of `utils.py` and back into `s3s.py`. I think that the fallback version should remain in `utils.py` and that `get_web_view_ver` should be called from `s3s.py` wherever the web view version is needed instead of maintaining it as a global.

**Comment by hasegaw** [comment]
I think it is resonable, and will be a good start point for the team if you want to do more changes later. :+1:

**Comment by niyari** [comment]
Would it be better for `get_web_view_ver()` to only communicate the first time and keep the data?
Currently, it looks like I'm fetching the HTML and JavaScript files each time `headbutt()` is called.

**Comment by hasegaw** [comment]
I believe it's better to be cached.

**Comment by clovervidia** [comment]
That's a good point. I didn't realize that we were grabbing the version every time.

**Comment by niyari** [comment]
Depending on future updates, there may be situations where it is better to keep web_view_ver fixed.
Splanet3 is an independent web app and can be updated independently of the NSOApp version.
This is because it uses (perhaps)GraphQL, and the structure of the data is likely to change significantly.
Fortunately, we need to take into account the period during which the script body is cached (Blue-Green) due to the same specifications as the browser, and s3s can accommodate that period.

Also, currently can get Splanet3 HTML and scripts without authentication, but this may require authentication as well.
(If there is no authentication or play record, it might show different HTML.)
For this reason, we would need to tell web_view_ver the token (header and Gamewebtoken) that makes it work the same as NSOApp.
Since the retrieved version string is often used in s3s.py, a variable is also provided in s3s.py.

**Comment by frozenpandaman** [comment]
Sorry for the late reply @niyari, and thank you! We definitely do _not_ want to have to perform a web request every time `headbutt()` is called so very good call on moving this to a global variable. I really appreciate your work here to help improve the codebase – all really good changes!

**Pull request merged**
