### PR TITLE
Added processing when the module is executed directly.

### PR DESCRIPTION
**Pull request by niyari**

### CODE REVIEW

**Comment by clovervidia** [comment]
Sorry to keep you waiting. I like the idea of adding main guards so that `iksm.py` and `utils.py` print messages if run directly, but do you think you could make the messages more clear as to what the user should do? Maybe they could instruct the user to run `s3s.py` instead?

**Comment by hasegaw** [comment]
Some would use these files with other host programs under GPLv3, but more detailed instructions cannot cover everything. I personally believe the description has reasonable information.  :)

**Comment by niyari** [comment]
The message is to briefly tell you that the file you are executing is wrong.
Would it be more helpful to add `This program cannot be run alone.` .

**Comment by frozenpandaman** [comment]
Thanks a ton!! Great suggestion.

**Pull request merged**
