### PR TITLE
Minor refactoring of util.py

### PR DESCRIPTION
**Pull request by cesaregarza**
# What Changed?
- Started adding typing
- Minor refactoring for clarity
- Made docstrings more descriptive

### CODE REVIEW

**Comment by clovervidia** [comment]
I like the addition of type hints and the new docstrings. They should make the module easier to use by other programs. I believe docstrings are meant to use triple double quotes, though.

I also have a few comments while we're on the subject of minor refactoring.

**Comment by cesaregarza** [comment]
I actually have a major refactoring effort going I didn't really want to unveil yet for risk of offending. I'm a software engineer in my day job and my entire job is refactoring data scientist code to production environments.

If you're curious, my progress on that major refactor effort is here: https://github.com/cesaregarza/s3s/tree/enhancement/major_refactor

**Comment by clovervidia** [comment]
That's pretty cool that you do this sort of thing at work. I'll definitely take a look at your fork later because I have some improvements in mind as well.

**Comment by frozenpandaman** [comment]
Sorry for the late reply @cesaregarza! I was out of town traveling and have been quite busy with school since (and am also a bit burned out from the game a bit tbh), so slowly working through all the PRs and issues. The idea to add type hints and more formal docstring definitions is interesting but I'm not sure if I'd want to add them for this project – I do think they can be beneficial (e.g. working with C++ (lol ew) at my old job I definitely did benefit there!) but for s3s in particular, I'm almost hoping it's simple enough to not require them. Ideally, variable types and function details can be transparent and readily understood by even just briefly looking at the code, and won't require this level of explanation or indication. Docstrings do currently provide information about method functionality in prose, as well, where I thought was needed.

Moreover, I'm also worried that, because I personally am not familiar with the typing library and how to use parts of it (`Union`, `Optional` etc.), or its conventions, this would make future development harder on my end.

Personally I do not care about PEP and such (I like my tabs and slightly-too-long-but-still-readable lines!) but am more than happy to make small changes like having files end with line breaks if that's better (re: POSIX standards) – and I do want consistency across the project; I've been trying hard to ensure that so far, e.g. in the imports at the top of each file.

I've made some of these changes (bringing the regex pattern out into a variable, specifying `SUPPORTED_KEYS` at the top & the better return statement in `custom_key_exists()`) in 1e2dfb4. Please let me know if you have other improvements or ways to optimize the code, or to make it more understandable and easy-to-use by other people/projects! Thanks again!!

**Comment by cesaregarza** [comment]
Hey @frozenpandaman, no sweat. I closed the PR because I realized I was going waaay too deep and just straight up intruding so instead of stepping on toes, I instead decided to create a tangential project instead. Your concerns are valid and I kind of went a little overboard so I'm sorry for imposing.

Anyway, I'll still keep an eye out since one of my far-out roadmap ideas involves interacting with s3s directly from the code for live updates while playing. I appreciate the response and I apologize if this PR seemed a little aggressive.

**Comment by frozenpandaman** [comment]
@cesaregarza No, no worries at all! I saw your message in Samuel's Discord server where this has spun off into offline/local analytics/data viz dashboards using Jupyter Notebook which sounds pretty cool, and I'll definitely check that out as it develops. I'm happy you're able to use the s3s-fetched & formatted JSON for projects like this; that was a goal of making s3s importable as a module/library this time (I'll finish making it fully modular, i.e. remove the bare print statements & `config.txt` creation and whatnot, by v0.2.0). And if you do have further code style improvements do let me know, it's really appreciated!

**Pull request closed without merging**
