### PR TITLE
Download more histories by querying specific battle type

### PR DESCRIPTION
**Pull request by bhiaibogf**
I found that you can get 50 recent battles stats for every specific game mode (regular, bankara and private). So you can get up to 150 battle stas by querying them separately.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Haha, I had my own excited realization about this too. :)
image

I had just tried to get something out fast ASAP after launch – and it does take a while to play 50 battles and/or work 50 Salmon Run jobs, so I figured people running the export command at least once every 50 wasn't that big of an ask.

But this is great to have, thank you!! I'll take more of a look later today when I can. The 'export as local file' feature is pretty temporary, and not a functionality I really expect anyone to use once stat.ink supports Splatoon 3, so hopefully this will support s3s running with `-r`, and bare with no flags as well (note: the I/O [here](https://github.com/frozenpandaman/s3s/blob/1f6818f2f8c8c3b1425ba3ac6ca32c6c727266a9/s3s.py#L585-L593) will have to change as well…)

In fact, do we need to query `LatestBattleHistoriesQuery` at all? I don't think so, right? For the most data possible, I guess we should query `RegularBattleHistoriesQuery` _and_ `BankaraBattleHistoriesQuery` _and_ `PrivateBattleHistoriesQuery`, combine them, and then use that as our "master list" of "recent battles". (It is _SO_ annoying each battle required a new request though, unlike SplatNet 2 which just had the handy `results.json` with all 50 recent battle details in one file…)

**Comment by frozenpandaman** [comment]
Definitely very good to query these pages though since right now (by querying the 'latest' page only) I think none of this info I've highlighted in green is getting saved:
image

🙃

**Comment by bhiaibogf** [comment]
> I had just tried to get something out fast ASAP after launch – and it does take a while to play 50 battles and/or work 50 Salmon Run jobs, so I figured people running the export command at least once every 50 wasn't that big of an ask.

Booyah! Thanks a lot for your rapid implement. But unfortunately, I have played more than 50 battles befor I found this rope. Thus, I wrote this code to download more histories.

> But this is great to have, thank you!! I'll take more of a look later today when I can. The 'export as local file' feature is pretty temporary, and not a functionality I really expect anyone to use once stat.ink supports Splatoon 3, so hopefully this will support s3s running with `-r`, and bare with no flags as well (note: the I/O [here](https://github.com/frozenpandaman/s3s/blob/1f6818f2f8c8c3b1425ba3ac6ca32c6c727266a9/s3s.py#L585-L593) will have to change as well…)
> 
> In fact, do we need to query `LatestBattleHistoriesQuery` at all? I don't think so, right? For the most data possible, I guess we should query `RegularBattleHistoriesQuery` _and_ `BankaraBattleHistoriesQuery` _and_ `PrivateBattleHistoriesQuery`, combine them, and then use that as our "master list" of "recent battles". (It is _SO_ annoying each battle required a new request though, unlike SplatNet 2 which just had the handy `results.json` with all 50 recent battle details in one file…)

Yeap, I agree with you. You may delete the code about `LatestBattleHistoriesQuery` and the argument `specific` I added in function `fetch_json`. And then it should work well with only '-r' flag.

> Definitely very good to query these pages though since right now (by querying the 'latest' page only) I think none of this info I've highlighted in green is getting saved: image
> 
> 🙃

Yeah, you could easily get this information now by using `BankaraBattleHistoriesQuery`, which names as "bankaraMatchChallenge" in json file.

**Comment by frozenpandaman** [comment]
I did some code cleanup (especially of the `try`/`except` statements), made the optional variables & calls to `fetch_json()` a little more easy to figure out, and bumped the version number. Also added a TODO comment saying that the I/O for the bare `s3s.py` command with no flags will need to be changed or improved since you can actually (attempt to) upload more than 50 battles now – in theory up to 150, if you've played 50 new ones of each type!

**Comment by frozenpandaman** [comment]
Re: the reverted `.gitignore` file, see https://github.com/frozenpandaman/s3s/pull/5#issuecomment-1242762174

(Ugh, didn't know to cherry-pick/ignore that commit, so now there's a bit of a messy file history, oh well…)

**Pull request merged**
