### PR TITLE
Add Updater module.

### PR DESCRIPTION
**Pull request by niyari**
The operation is almost the same as splatnet2statink.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Thanks! I think I want to hold off on this until I release v0.1.0, which will be when it actually posts battles to stat.ink & when they start supporting Splatoon 3 battles.

Also some other caveats & notes – I'll change these before merging if you don't:
 - I'm not sure I want this in its own file. Including it in `s3s.py` might be fine.
 - All the `from __future__` calls should be removed as we're not supporting Python 2 anymore or using the `future` library
 - `.format()` should be changed to use f-strings & other code modernized where needed

**Comment by frozenpandaman** [comment]
Auto-updating is staged for a future update. See 999f6f7 & #14

**Comment by niyari** [comment]
Already resolved, but we split the file to improve readability of the code.

**Comment by frozenpandaman** [comment]
Yeah, I know it's a big file 😅 Though having *just* the update function in its own file seems, I don't know, like there's almost not enough there then? haha. The way it's currently split is:
 - `iksm.py` – account login/auth stuff (`f` generation, `config.txt` writing, etc.)
 - `s3s.py` – everything else

Hopefully this isn't too bad! For s2s Salmon Run support was in its own file, but that's because it got added much later and didn't support monitoring mode…

**Comment by niyari** [comment]
Understood. I will follow that.

**Comment by frozenpandaman** [comment]
@hasegaw is interested in helping with some refactoring too… so it may change yet from here 🙂 I agree that I don't want it to get too unwieldily or difficult to understand, and I will try to strive for that. Thanks for your support!

**Comment by hasegaw** [comment]
I checked the PR and believe it will be useful in near future. Let's add the feature once the project is practical.

**Pull request closed without merging**
