### PR TITLE
support X Battle

### PR DESCRIPTION
**Pull request by otofune**
- Support latest stat.ink's change. https://blog.fetus.jp/202211/974.html
- I only set `x_power_after` when changed. But `stat.ink` shows `?` for null. Maybe it should be filled by `x_power_before` value.
   https://stat.ink/@otofune/spl3/61f28c05-82d2-4cd6-8719-84d849b02b25
    image

### CODE REVIEW

**Comment by frozenpandaman** [comment]
oh, i didn't know stat.ink supported x battles yet……… thanks!

**Comment by frozenpandaman** [comment]
I agree it would be good to send the same as `x_power_before` instead of showing a "?" (for no change, since your X Power only changes after you finish the series).

Or maybe @fetus-hina could change it so anything showing as "**→ ?**" is hidden, instead?

e.g. Instead of
**X Power      2,059.7 → ?**
stat.ink could show
**X Power      2,059.7**

Which is best?

**Comment by frozenpandaman** [comment]
Thanks @otofune!

**Comment by fetus-hina** [comment]
The display behavior is updated.

| Before | After | Old | Now | |
|-|-|-|-|-|
| none | none | none | none | not changed |
| none | 2059.7 | ? → 2059.7 | ? → 2059.7 | not changed |
| 2059.7 | none | 2059.7 → ? | <ins>2059.7</ins> | simplified |
| 2059.7 | 2059.7 | 2059.7 → 2059.7 | <ins>2059.7</ins> | simplified |
| 2059.7 | 2100.0 | 2059.7 → 2100.0 | 2059.7 → 2100.0 | not changed |

**Pull request merged**
