### PR TITLE
Fix for defect #97 Occasionally exceptions raise running from crontab

### PR DESCRIPTION
**Pull request by Ogekuri**
I've added a try/catch on **fetch_and_upload_single_result** as workaroud to fix defect #97

### CODE REVIEW

**Comment by ADeeeee** [comment]
I've tried it and no errors today. 

Just curious, shouldn't result_post.text supposed to get some data from SplatNet3? How does the whole flow work by s3s when it failed to be a correct json data? Does it still get the correct data and upload it to stat.ink?

**Comment by ADeeeee** [comment]
I guess I will leave the exception raise because I have retries in few minutes in my command when the script failed.

**Comment by frozenpandaman** [comment]
This will avoid the error, but I don't know if letting it silently pass is what we want. Do we know why the JSONs are sometimes returning blank? 

@ADeeeee, you said in #97 that "I have a cronjob which runs in every hours and it seems to happen in every 3 hours (12, 15, 18, 21 o'clock today)" – is this still happening??

Maybe if this happens when s3s is being run with `-r` the script should just exit… and then users can retry, and it should work then… Thoughts?

**Comment by frozenpandaman** [comment]
>Maybe we could do some retries if the GraphQL api returns unexpected things with 401 in order to reduce this error.

I think this is probably best, rather than silently passing as in #97. Is one retry enough? What have you seen through your testing?

**Comment by ADeeeee** [comment]
> This will avoid the error, but I don't know if letting it silently pass is what we want. Do we know why the JSONs are sometimes returning blank?
Currently we have two senarios for this issue:

1. With ```-M```, which might not want the error exit at all.
2. Without ```-M```, which needs the error code for retrying (e.g. me) or just need to ignore the error with much more executions (e.g. Ogekuri)

Probably no one knows how long or frequent the 401 Unautherized remains and why it happens with the same credential now unless we have a monitor for the SplatNet3 API in every minutes, but could still improve the UX by doing these workarounds first.

> @ADeeeee, you said in https://github.com/frozenpandaman/s3s/issues/97 that "I have a cronjob which runs in every hours and it seems to happen in every 3 hours (12, 15, 18, 21 o'clock today)" – is this still happening??

Pardon me that I stopped the test two weeks ago because the notification emails were too annoy while there's no further discusses in the issue. I wll checkout the commit what @Ogekuri had and keep it about a week tonight.

It was pretty regular, but not always. We'll see how it goes again then.

> Maybe if this happens when s3s is being run with -r the script should just exit… and then users can retry, and it should work then… Thoughts?
> I think this is probably best, rather than silently passing as in https://github.com/frozenpandaman/s3s/issues/97. Is one retry enough? What have you seen through your testing?

Yep, I use ```python3 s3s.py -r || (sleep 180 && python3 s3s.py)```, waiting 3 minutes and running it again if there's any error exits, in order to do the retry so far, although it could still be failed. Yeah, we could do the retries while getting the GraphQL few times (maybe total 3 times between 30 seconds each) and see if it could get the correct data and then conintues, vice versa restart the whole script in a time range. 

This could help a lot for having much confidence for uploading data by running s3s.py rather than having no idea whether the script has been triggered or not, epecially it runs for instance between 2 hours, like me, and you don't need to trigger it again manually or wait until next time if the users want to review their battles on stat.ink  just after the previous schedule.

**Comment by frozenpandaman** [comment]
I added one retry in `fetch_and_upload_single_result()` which should fix this error some of the time. Instead of automatically deciding whether to exit or not, you can now specify behavior per your use case. The new `errors_pass_silently` [config key](https://github.com/frozenpandaman/s3s/wiki/config-keys) now exists which allows you to specify if you want the script to exit or not upon encountering an error in this circumstance. Just set this to true in your `config.txt` and s3s will still print out the error but continue running. Hopefully this addresses the problems you were running into, @Ogekuri and @ADeeeee!

**Pull request closed without merging**
